mode: 'train'
ARCHITECTURE:
    name: 'ResNet50_vd'

pretrained_model: "./pretrained/ResNet50_vd_10w_pretrained"
load_static_weights: True
model_save_dir: "./output/"
classes_num: 5
total_images: 2000
save_interval: 1
validate: True
valid_interval: 1
epochs: 100
topk: 1
image_shape: [3, 224, 224]

multilabel: True

use_mix: False
ls_epsilon: 0.1

LEARNING_RATE:
    function: 'CosineWarmup'          
    params:                   
        lr: 0.07               

OPTIMIZER:
    function: 'Momentum'
    params:
        momentum: 0.9
    regularizer:
        function: 'L2'
        factor: 0.000070

TRAIN:
    batch_size: 64
    num_workers: 4
    file_list: "/path/to/multi_train_list_example.txt"
    data_dir: "/path/to/image/directory"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:
    mix:                       
        - MixupOperator:    
            alpha: 0.2      

VALID:
    batch_size: 64
    num_workers: 4
    file_list: "/path/to/val_list.txt"
    data_dir: "/path/to/image/directory"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            resize_short: 256
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:
